# Generated by Django 4.2.4 on 2023-09-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=50)),
                ('dimention', models.CharField(max_length=50)),
                ('warehouse', models.CharField(max_length=50)),
                ('qty_in_wh', models.FloatField()),
                ('price', models.FloatField()),
                ('image_urel', models.URLField()),
            ],
        ),
    ]
