# Generated by Django 4.2.4 on 2023-09-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=11, unique=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=50)),
                ('dimention', models.CharField(max_length=50)),
                ('warehouse', models.CharField(max_length=50)),
                ('qty_in_wh', models.FloatField()),
                ('price', models.FloatField()),
                ('image_urel', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(auto_now=True, null=True)),
                ('customer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_Info', to='fileImageData.customers')),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectedItem', to='fileImageData.productlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervizer', to='fileImageData.users')),
            ],
        ),
    ]
