# Generated by Django 4.2.4 on 2023-09-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='image_urel',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
