# Generated by Django 4.2.1 on 2023-09-18 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0003_alter_productlist_image_urel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='productlist',
            name='image_urel',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
