# Generated by Django 4.2.1 on 2023-09-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0004_users_alter_productlist_image_urel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='image_urel',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CollectedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectedItem', to='fileImageData.productlist')),
                ('product_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectedItemName', to='fileImageData.productlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervizer', to='fileImageData.users')),
            ],
        ),
    ]
