# Generated by Django 4.2.1 on 2023-09-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0005_alter_productlist_id_alter_productlist_image_urel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectedproduct',
            name='product_Name',
        ),
    ]
