# Generated by Django 4.2.1 on 2023-09-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0006_remove_collectedproduct_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=11, unique=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='collectedproduct',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
